:root{--navy:#1e3a5c;--navy-dark:#132a45;--rust:#b5502f;--gold:#e0a63c;--cream:#fbf7ef;--paper:#fffdf8;--ink:#2a2520;--muted:#746d63;--line:#e5ded2;--green:#3e6f5e;--blue-soft:#eef2f6;--shadow:0 18px 50px rgba(35,48,58,.10)}
*{box-sizing:border-box}
html{scroll-behavior:smooth;scroll-padding-top:94px}
body{margin:0;background:#efeae0;color:var(--ink);font-family:"Assistant",Arial,sans-serif;font-size:17px;line-height:1.78}
a{color:inherit;text-decoration:none}
button,input{font:inherit}
.read-progress{position:fixed;inset:0 0 auto;height:3px;background:transparent;z-index:100}.read-progress span{display:block;width:0;height:100%;background:var(--gold)}
.reader-bar{position:sticky;top:0;z-index:90;min-height:72px;padding:0 max(20px,calc((100vw - 1180px)/2));display:flex;align-items:center;gap:22px;background:rgba(251,247,239,.94);border-bottom:1px solid rgba(229,222,210,.9);backdrop-filter:blur(14px)}
.reader-brand{display:flex;align-items:center;gap:10px;white-space:nowrap;color:var(--navy)}.reader-brand>span{width:35px;height:35px;display:grid;place-items:center;border-radius:50% 50% 50% 7px;background:var(--rust);color:#fff;font:900 20px/1 "Frank Ruhl Libre",serif;transform:rotate(-5deg)}.reader-brand strong{font:700 15px "Frank Ruhl Libre",serif}
.reader-bar nav{display:flex;align-items:center;justify-content:center;gap:4px;flex:1}.reader-bar nav a{min-width:32px;height:32px;display:grid;place-items:center;border-radius:999px;color:var(--navy);font-size:12px;font-weight:700}.reader-bar nav a:hover,.reader-bar nav a[aria-current="page"]{background:var(--navy);color:#fff}.reader-bar nav a:first-child,.reader-bar nav a:last-child{padding:0 12px;width:auto}
.reader-actions{display:flex;align-items:center;gap:6px}.reader-actions a{width:34px;height:34px;display:grid;place-items:center;border:1px solid var(--line);border-radius:50%;color:var(--navy);background:#fff}.reader-actions a:hover{background:var(--rust);color:#fff;border-color:var(--rust)}.progress-chip{height:38px;display:flex;align-items:center;gap:7px;border:1px solid var(--line);border-radius:999px;padding:0 12px;background:#fff;color:var(--muted)}.progress-chip small{font-size:10px}.progress-chip b{color:var(--green);font-size:14px}
.menu-button{display:none;border:0;background:var(--navy);color:#fff;border-radius:999px;padding:7px 14px;font-weight:700}
.book-shell{width:min(920px,calc(100% - 36px));margin:40px auto;background:var(--paper);box-shadow:var(--shadow);border-radius:16px;overflow:hidden}
.book-content{padding:64px clamp(28px,7vw,78px) 78px;text-align:right}.front-content{padding-top:74px}
.cover-hero,.unit-opener{min-height:840px;position:relative;overflow:hidden;background:var(--navy);color:#f6efe2;padding:64px 70px;display:flex;flex-direction:column}
.cover-sun{position:absolute;left:-140px;top:110px;width:440px;height:440px;border-radius:50%;background:var(--gold)}.cover-arch{position:absolute;left:110px;top:370px;width:230px;height:115px;border-radius:0 0 230px 230px;background:var(--rust)}.cover-ring{position:absolute;right:-100px;bottom:-150px;width:350px;height:350px;border-radius:50%;border:52px solid #2c4b70}
.cover-top,.unit-top{position:relative;z-index:2;display:flex;justify-content:space-between;align-items:center}.cover-top span{border:1px solid var(--gold);border-radius:999px;padding:4px 16px;color:var(--gold);font-weight:700;font-size:13px}.cover-top b{color:#d9cbb2;font-size:11px;letter-spacing:.22em}
.cover-main{position:relative;z-index:2;margin-top:auto}.cover-main p{color:var(--gold);font:700 19px "Frank Ruhl Libre",serif}.cover-main h1{margin:0;font:900 clamp(56px,9vw,78px)/1.03 "Frank Ruhl Libre",serif;letter-spacing:-.02em}.cover-main h2{margin:16px 0 0;color:#c8d2de;font-size:21px;font-weight:400}.cover-main small{color:#8fa2b8}.cover-author{position:relative;z-index:2;margin-top:65px;padding-top:18px;border-top:1px solid rgba(246,239,226,.25);display:grid}.cover-author strong{font-size:18px}.cover-author span{color:#8fa2b8;font-size:13px}
.unit-opener{min-height:820px}.opener-orb{position:absolute;left:-120px;bottom:-150px;width:380px;height:380px;border-radius:50%;background:var(--gold)}.opener-arch{position:absolute;left:185px;bottom:108px;width:145px;height:73px;border-radius:145px 145px 0 0;background:var(--rust)}.unit-top span{color:var(--gold);font-size:13px;font-weight:700;letter-spacing:.12em}.unit-top b{font:900 64px/1 "Frank Ruhl Libre",serif;color:rgba(246,239,226,.16)}
.unit-title{position:relative;z-index:3;margin-top:62px;max-width:660px}.unit-title h1{margin:0;font:900 clamp(42px,7vw,60px)/1.1 "Frank Ruhl Libre",serif}.unit-title p{margin:10px 0 0;color:#c8d2de;font-size:20px}.unit-goal{position:relative;z-index:3;margin-top:52px;padding-top:16px;border-top:1px solid rgba(246,239,226,.25);max-width:650px}.unit-goal>span{color:var(--gold);font-weight:700;font-size:13px}.unit-goal p{margin:4px 0;font-size:17px;line-height:1.7}.opener-extra{position:relative;z-index:3;max-width:460px;margin-top:22px;font-size:14px;color:#d9e0e8}.opener-extra h3{color:var(--gold);font:700 15px "Assistant",sans-serif;margin:12px 0 4px}.opener-extra .list-card{background:transparent;border:0;padding:0;box-shadow:none}.opener-extra ul{margin:4px 0}.unit-opener>img{position:absolute;z-index:2;left:54px;bottom:92px;width:270px;height:180px;object-fit:cover;border:2px solid rgba(246,239,226,.45);border-radius:14px;box-shadow:0 14px 34px rgba(10,28,48,.3)}.opener-note{position:absolute;left:70px;bottom:45px;color:#8fa2b8;font-weight:700;font-size:11px;letter-spacing:.18em}
.major-head,.chapter-head,.review-head,.learning-head,.appendix-head{scroll-margin-top:90px}.major-head{padding-bottom:15px;margin:0 0 28px;border-bottom:3px solid var(--navy)}.major-head:not(:first-child){margin-top:64px}.major-head h1,.major-head h2{margin:0;color:var(--navy);font:900 36px/1.2 "Frank Ruhl Libre",serif}
.chapter-head{margin:72px 0 28px;padding-bottom:16px;border-bottom:3px solid var(--navy)}.chapter-head:first-child{margin-top:0}.chapter-pill{display:inline-flex;background:var(--rust);color:var(--cream);border-radius:999px;padding:4px 15px;font-size:13px;font-weight:700}.chapter-head h2{margin:11px 0 0;color:var(--navy);font:900 34px/1.2 "Frank Ruhl Libre",serif}.mini-head{border-color:var(--gold)}.mini-head .chapter-pill{background:var(--gold);color:var(--navy-dark)}
.review-head,.learning-head,.appendix-head{margin:68px 0 26px;border-radius:13px;padding:21px 24px}.review-head{background:#f7ebd4;border-right:5px solid var(--gold)}.learning-head{background:#eaf1ec;border-right:5px solid var(--green)}.appendix-head{background:var(--blue-soft);border-right:5px solid var(--navy)}.review-head span,.learning-head span,.appendix-head span{font-weight:700;font-size:12px;letter-spacing:.06em;color:var(--muted)}.review-head h2,.learning-head h2,.appendix-head h2{margin:4px 0 0;color:var(--navy);font:900 29px/1.25 "Frank Ruhl Libre",serif}
h3{margin:31px 0 10px;color:var(--navy);font:700 23px/1.3 "Frank Ruhl Libre",serif}p{margin:0 0 14px;text-wrap:pretty}.lead-label{margin-top:18px;color:var(--navy);font-weight:700}
.es-text,.inline-es{color:var(--rust);font-family:"Frank Ruhl Libre",serif;font-weight:700;unicode-bidi:isolate}.inline-es{display:inline-block}.translation{color:var(--muted);margin-inline-start:7px}.spanish-keyword,.spanish-block{position:relative;margin:12px 0;padding:13px 54px 13px 18px;border-radius:10px;background:var(--navy);color:var(--cream);font:700 21px/1.5 "Frank Ruhl Libre",serif;text-align:left}.spanish-block{font-size:18px;background:var(--blue-soft);color:var(--navy)}
.examples,.dialogue,.exercise,.list-card,.check-card,.callout{margin:16px 0;border-radius:12px;break-inside:avoid}.examples{padding:11px 18px;background:#fbf8f1;border:1px solid #ede4d2}.examples>div,.example-row{padding:8px 2px;border-bottom:1px dashed #e6ded0}.examples>div:last-child{border:0}.example-row{margin:8px 0}.dialogue{padding:15px 20px;background:var(--blue-soft);border-right:4px solid var(--navy)}.dialogue>div{padding:7px 0;border-bottom:1px solid #dce4ec}.dialogue>div:last-child{border:0}.exercise{padding:16px 20px;background:#eaf1ec;border-right:4px solid var(--green)}.writing-lines>div{min-height:34px;border-bottom:1px solid #bdd0c5}.list-card{padding:15px 20px;background:#fbf8f1;border:1px solid #ede4d2}.list-card ul{margin:7px 0 0;padding-right:22px}.list-card li{margin:4px 0}.list-label,.check-intro{color:var(--navy);font-weight:700}.check-card{padding:17px 20px;border:1.5px solid var(--navy);display:grid;gap:8px}.check-row{display:flex;align-items:flex-start;gap:10px;cursor:pointer}.check-row input{margin-top:8px;accent-color:var(--green)}
.callout{padding:17px 20px;border:1px solid var(--line);background:#fff}.callout-label{font-weight:700;font-size:13px;letter-spacing:.02em;margin-bottom:5px}.callout-content{line-height:1.7}.callout.tip,.callout.memory{background:#fbf1da;border-color:#ead39e}.callout.tip .callout-label,.callout.memory .callout-label{color:#8a6414}.callout.mistake{background:#f9ece7;border-color:#e8c2b4}.callout.mistake .callout-label{color:var(--rust)}.callout.journey{background:#eaf1ec;border-color:#cfe0d6}.callout.journey .callout-label{color:var(--green)}.callout.culture,.callout.world{background:var(--blue-soft);border-color:#d5e0ea}.callout.culture .callout-label,.callout.world .callout-label{color:var(--navy)}.callout.ai{background:#f2eef8;border-color:#ddd2eb}.callout.ai .callout-label{color:#634783}
.interactive-exercise,.self-practice{margin:25px 0;padding:22px;border:1px solid #cfdcd4;border-radius:15px;background:#f8fbf9;box-shadow:0 8px 24px rgba(38,76,59,.06);break-inside:avoid}.interactive-exercise.is-complete,.self-practice.is-complete{border-color:#87b49f;background:#f2f8f4}.interactive-head{display:flex;justify-content:space-between;gap:20px;align-items:flex-start;margin-bottom:18px}.interactive-head span{display:block;color:var(--green);font-size:11px;font-weight:700;letter-spacing:.06em}.interactive-head h4{margin:2px 0 0;color:var(--navy);font:700 22px/1.3 "Frank Ruhl Libre",serif}.interactive-head>b{direction:ltr;color:#9aaea3;font-size:10px;font-weight:700;letter-spacing:.08em;white-space:nowrap}.interactive-rows{display:grid;gap:12px}.interactive-row{padding:13px 14px;border:1px solid #dbe5df;border-radius:10px;background:#fff}.interactive-row label{display:flex;gap:9px;align-items:flex-start;margin-bottom:8px;color:var(--ink);font-weight:600}.question-number{flex:none;width:24px;height:24px;display:grid;place-items:center;border-radius:50%;background:#e6f0e9;color:var(--green);font-size:12px}.question-text{padding-top:1px}.student-answer,.self-answer{width:100%;border:1.5px solid #c7d3cc;border-radius:8px;background:#fff;color:var(--navy-dark);padding:10px 12px;font:600 16px "Frank Ruhl Libre",serif;outline:none}.student-answer:focus,.self-answer:focus{border-color:var(--navy);box-shadow:0 0 0 3px rgba(30,58,92,.10)}select.student-answer{cursor:pointer}.interactive-row.is-correct{border-color:#7daf96;background:#f4faf6}.interactive-row.is-near{border-color:#deb65e;background:#fffaf0}.interactive-row.is-wrong{border-color:#d28e75;background:#fff7f4}.row-feedback{min-height:0;margin-top:5px;font-size:12px;font-weight:700}.is-correct .row-feedback{color:var(--green)}.is-near .row-feedback{color:#8a6414}.is-wrong .row-feedback{color:var(--rust)}
.exercise-actions{display:flex;flex-wrap:wrap;gap:8px;margin-top:17px}.exercise-actions button{border:1px solid #c7d3cc;border-radius:999px;background:#fff;color:var(--navy);padding:8px 15px;font-weight:700;cursor:pointer}.exercise-actions .check-answer,.exercise-actions .complete-self{background:var(--navy);border-color:var(--navy);color:#fff}.exercise-actions button:hover{border-color:var(--rust);color:var(--rust)}.exercise-actions .check-answer:hover,.exercise-actions .complete-self:hover{background:var(--rust);border-color:var(--rust);color:#fff}.exercise-feedback{margin-top:12px;font-weight:700}.hint-panel,.answer-panel{margin-top:12px;padding:12px 15px;border-radius:9px;background:#fbf1da;color:#6d5521}.answer-panel{background:var(--blue-soft);color:var(--navy)}.answer-panel ol{margin:8px 0 0;padding-right:24px}.answer-panel li{margin:4px 0}.self-label{display:block;margin-bottom:7px;font-weight:700;color:var(--navy)}.self-answer{min-height:150px;resize:vertical;line-height:1.65}.self-checklist{display:grid;gap:6px;margin-top:13px;padding:12px 14px;border-radius:9px;background:#fff}.self-checklist>span{font-weight:700;color:var(--green)}.self-checklist label{display:flex;gap:8px;align-items:flex-start}.self-checklist input{margin-top:6px;accent-color:var(--green)}.check-progress{margin-top:5px;color:var(--green);font-size:12px;font-weight:700}.blank-marker{display:inline-block;min-width:70px;border-bottom:1px solid currentColor;color:transparent}.sr-only{position:absolute!important;width:1px!important;height:1px!important;padding:0!important;margin:-1px!important;overflow:hidden!important;clip:rect(0,0,0,0)!important;white-space:nowrap!important;border:0!important}
.table-wrap{margin:17px 0 24px;overflow-x:auto;border:1px solid var(--line);border-radius:11px;break-inside:avoid}table{width:100%;border-collapse:collapse;font-size:15px}th{padding:10px 14px;background:var(--navy);color:var(--cream);text-align:right;font-weight:600}td{padding:9px 14px;border-bottom:1px solid var(--line);vertical-align:top;text-align:right}tbody tr:last-child td{border-bottom:0}tbody tr:nth-child(even){background:#fcfaf5}.es-cell{text-align:left;color:var(--rust);font:700 16px "Frank Ruhl Libre",serif}.cell-lines>div{padding:2px 0}
.audio-button{position:absolute;right:13px;top:50%;transform:translateY(-50%);width:31px;height:31px;border:0;border-radius:50%;display:grid;place-items:center;background:rgba(255,255,255,.16);color:inherit;cursor:pointer}.es-text>.audio-button,.inline-es>.audio-button,.es-cell>.audio-button{position:static;display:inline-grid;transform:none;margin-left:7px;width:28px;height:28px;background:#f2ece3;color:var(--navy);vertical-align:middle}.audio-button:hover,.audio-button.is-playing{background:var(--gold);color:var(--navy)}
.appendices-opener{padding:72px 74px;background:var(--navy);color:var(--cream)}.appendices-opener>span{color:var(--gold);font-weight:700;font-size:13px}.appendices-opener h1{font:900 58px/1.1 "Frank Ruhl Libre",serif;margin:8px 0}.appendices-opener p{max-width:640px;color:#c8d2de;font-size:18px}
.bottom-nav{width:min(920px,calc(100% - 36px));margin:0 auto 26px;display:flex;justify-content:space-between;align-items:center}.bottom-nav a{color:var(--muted);font-weight:700}.bottom-nav .next{background:var(--navy);color:#fff;border-radius:999px;padding:10px 24px}.bottom-nav .next:hover{background:var(--rust)}
footer{width:min(920px,calc(100% - 36px));min-height:90px;margin:0 auto;display:flex;justify-content:space-between;align-items:center;border-top:1px solid #d8d0c3;color:var(--muted);font-size:12px}footer a{color:var(--navy);font-family:"Frank Ruhl Libre",serif;font-weight:700}
.toast{position:fixed;z-index:120;left:24px;bottom:24px;max-width:340px;padding:11px 16px;border-radius:10px;background:var(--navy-dark);color:#fff;box-shadow:var(--shadow);opacity:0;pointer-events:none;transform:translateY(10px);transition:.2s}.toast.show{opacity:1;transform:none}
@media(max-width:820px){.reader-bar{padding:0 18px}.menu-button{display:block;margin-right:auto}.reader-bar nav{display:none;position:absolute;top:64px;right:14px;left:14px;padding:14px;flex-wrap:wrap;background:var(--paper);border:1px solid var(--line);border-radius:13px;box-shadow:var(--shadow)}.reader-bar nav.open{display:flex}.reader-brand strong{display:none}.reader-actions{margin-right:0}.progress-chip small{display:none}.book-shell{margin-top:18px}.cover-hero,.unit-opener{min-height:720px;padding:45px 36px}.unit-title{margin-top:46px}.unit-goal{margin-top:36px}.unit-opener>img{width:220px;height:145px;left:30px;bottom:74px}.opener-note{left:36px;bottom:32px}}
@media(max-width:600px){body{font-size:16px}.book-shell,.bottom-nav,footer{width:calc(100% - 20px)}.book-content{padding:42px 22px 58px}.cover-hero,.unit-opener{min-height:680px;padding:36px 25px}.cover-top b{display:none}.cover-sun{left:-210px}.cover-arch{left:45px}.cover-main h1{font-size:52px}.unit-top b{font-size:50px}.unit-title h1{font-size:39px}.unit-title p{font-size:17px}.unit-goal p{font-size:15px}.opener-extra{max-width:100%;font-size:13px}.unit-opener>img{opacity:.3;width:240px;height:160px;left:-30px}.chapter-head h2{font-size:29px}.major-head h1,.major-head h2{font-size:31px}.table-wrap{margin-left:-10px;margin-right:-10px;border-radius:7px}th,td{padding:8px 10px;min-width:120px}.translation{display:block;margin:2px 0 0}.interactive-exercise,.self-practice{padding:16px;margin-left:-8px;margin-right:-8px}.interactive-head{display:block}.interactive-head>b{display:block;margin-top:4px}.exercise-actions button{flex:1 1 42%;padding:8px 9px}.bottom-nav a{font-size:13px}.bottom-nav .next{padding:9px 16px}footer{justify-content:center;text-align:center}footer a{display:none}.appendices-opener{padding:55px 28px}.appendices-opener h1{font-size:48px}}
@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}.toast{transition:none}}
@media print{.reader-bar,.read-progress,.bottom-nav,.audio-button,.toast,footer,.exercise-actions{display:none!important}body{background:#fff}.book-shell{width:auto;margin:0;box-shadow:none;border-radius:0}.cover-hero,.unit-opener{min-height:267mm;break-after:page}.book-content{padding:14mm}.chapter-head,.review-head,.learning-head,.appendix-head{break-before:page}.table-wrap{overflow:visible}a{color:inherit}}
